server:
  port: 8050
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/terryblithe/spring-cloud  # 配置git仓库的地址
          search-paths: config-repo                         # git仓库地址下相对地址，可以配置多个，用","分割
          username:                    # git仓库的账号
          password:                                # git仓库的密码